const $ = id => document.getElementById(id);
const DB_NAME = 'blexo-check-documents-v3';
const STORE = 'documents';
let currentDocument = blankDocument(), saveTimer, pendingScan = null;
const newId = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const blankDocument = () => ({id:newId(),name:'Novo documento',company:'',reference:'',responsible:'',notes:'',mode:'gray',cleanLevel:55,pages:[],updatedAt:new Date().toISOString()});
function openDatabase(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveDocument(){const db=await openDatabase();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(currentDocument);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function getDocuments(){const db=await openDatabase();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>{db.close();resolve(r.result||[])};r.onerror=()=>{db.close();reject(r.error)}})}
function syncFields(){currentDocument.name=$('documentName').value.trim();currentDocument.company=$('company').value.trim();currentDocument.reference=$('reference').value.trim();currentDocument.responsible=$('responsible').value.trim();currentDocument.notes=$('notes').value.trim();currentDocument.mode=document.querySelector('input[name="scanMode"]:checked')?.value||'gray';currentDocument.cleanLevel=Number($('cleanLevel').value);$('documentHeading').textContent=currentDocument.name||'Novo documento'}
function scheduleSave(msg='Salvo neste aparelho'){clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{syncFields();currentDocument.updatedAt=new Date().toISOString();await saveDocument();$('feedback').textContent=msg},350)}
function escapeHtml(v=''){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function render(){syncFields();$('documentName').value=currentDocument.name||'';$('company').value=currentDocument.company||'';$('reference').value=currentDocument.reference||'';$('responsible').value=currentDocument.responsible||'';$('notes').value=currentDocument.notes||'';const radio=document.querySelector(`input[name="scanMode"][value="${currentDocument.mode||'gray'}"]`);if(radio)radio.checked=true;$('cleanLevel').value=currentDocument.cleanLevel??55;updateCleanLabel();$('documentHeading').textContent=currentDocument.name||'Novo documento';renderPages()}
function renderPages(){const pages=currentDocument.pages;$('pageCount').textContent=`${pages.length} ${pages.length===1?'página':'páginas'}`;$('generateButton').disabled=!pages.length;$('pagesList').innerHTML=pages.length?pages.map((p,i)=>`<article class="document-page"><button class="page-remove" data-remove-page="${p.id}" aria-label="Excluir página">×</button><img src="${p.src}" alt="Página ${i+1}"><div class="page-number">Página ${String(i+1).padStart(2,'0')}</div><div class="page-mode">${p.mode==='document'?'Documento':p.mode==='gray'?'Tons de cinza':'Original'}${p.corrected?' · perspectiva corrigida':''}</div><input class="page-title" data-page-title="${p.id}" value="${escapeHtml(p.title||'')}" placeholder="Identificação da página (opcional)"></article>`).join(''):'<div class="empty-pages">Nenhuma página adicionada. Use “Fotografar página” ou escolha imagens da galeria.</div>';$('[data-remove-page]')&&document.querySelectorAll('[data-remove-page]').forEach(b=>b.onclick=()=>{currentDocument.pages=currentDocument.pages.filter(p=>p.id!==b.dataset.removePage);renderPages();scheduleSave()});document.querySelectorAll('[data-page-title]').forEach(f=>f.oninput=()=>{const p=currentDocument.pages.find(x=>x.id===f.dataset.pageTitle);if(p)p.title=f.value;scheduleSave()})}
function readImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(r.error);r.onload=()=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=r.result};r.readAsDataURL(file)})}
function imageToCanvas(img,maxSide=2200){const s=Math.min(1,maxSide/Math.max(img.naturalWidth,img.naturalHeight));const c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*s);c.height=Math.round(img.naturalHeight*s);c.getContext('2d',{alpha:false}).drawImage(img,0,0,c.width,c.height);return c}
function canvasData(c,q=.86){return c.toDataURL('image/jpeg',q)}
function updateCleanLabel(){$('cleanValue').textContent=`${$('cleanLevel').value}%`}
function defaultCorners(c){const m=Math.min(c.width,c.height)*.035;return [{x:m,y:m},{x:c.width-m,y:m},{x:c.width-m,y:c.height-m},{x:m,y:c.height-m}]}
function orderPoints(p){const sum=p.map(a=>a.x+a.y),dif=p.map(a=>a.x-a.y);return [p[sum.indexOf(Math.min(...sum))],p[dif.indexOf(Math.max(...dif))],p[sum.indexOf(Math.max(...sum))],p[dif.indexOf(Math.min(...dif))]]}
function solve8(A,b){const n=8;for(let i=0;i<n;i++){let max=i;for(let r=i+1;r<n;r++)if(Math.abs(A[r][i])>Math.abs(A[max][i]))max=r;[A[i],A[max]]=[A[max],A[i]];[b[i],b[max]]=[b[max],b[i]];const pivot=A[i][i]||1e-12;for(let j=i;j<n;j++)A[i][j]/=pivot;b[i]/=pivot;for(let r=0;r<n;r++){if(r===i)continue;const f=A[r][i];for(let j=i;j<n;j++)A[r][j]-=f*A[i][j];b[r]-=f*b[i]}}return b}
function homography(src,dst){const A=[],b=[];for(let i=0;i<4;i++){const x=src[i].x,y=src[i].y,u=dst[i].x,v=dst[i].y;A.push([x,y,1,0,0,0,-u*x,-u*y]);b.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);b.push(v)}const h=solve8(A,b);return [...h,1]}
function warpPerspectiveJS(srcCanvas,points){const p=orderPoints(points),[tl,tr,br,bl]=p;const w=Math.max(Math.hypot(tr.x-tl.x,tr.y-tl.y),Math.hypot(br.x-bl.x,br.y-bl.y));const h=Math.max(Math.hypot(bl.x-tl.x,bl.y-tl.y),Math.hypot(br.x-tr.x,br.y-tr.y));const portrait=h>=w*.78;const outW=portrait?1200:1700,outH=portrait?1700:1200;const H=homography(p,[{x:0,y:0},{x:outW-1,y:0},{x:outW-1,y:outH-1},{x:0,y:outH-1}]);const c=document.createElement('canvas');c.width=outW;c.height=outH;const ctx=c.getContext('2d');const src=srcCanvas.getContext('2d').getImageData(0,0,srcCanvas.width,srcCanvas.height),dst=ctx.createImageData(outW,outH);const [a,b,c1,d,e,f,g,h1]=H;for(let y=0;y<outH;y++){for(let x=0;x<outW;x++){const den=g*x+h1*y+1;const sx=(a*x+b*y+c1)/den,sy=(d*x+e*y+f)/den,ix=Math.floor(sx),iy=Math.floor(sy),di=(y*outW+x)*4;if(ix<0||iy<0||ix>=srcCanvas.width||iy>=srcCanvas.height){dst.data[di]=dst.data[di+1]=dst.data[di+2]=255;dst.data[di+3]=255;continue}const si=(iy*srcCanvas.width+ix)*4;dst.data[di]=src.data[si];dst.data[di+1]=src.data[si+1];dst.data[di+2]=src.data[si+2];dst.data[di+3]=255}}ctx.putImageData(dst,0,0);return c}
function processCanvas(c,mode,level){if(mode==='original')return c;const ctx=c.getContext('2d');const d=ctx.getImageData(0,0,c.width,c.height),o=new ImageData(c.width,c.height);const data=d.data,out=o.data;for(let i=0;i<data.length;i+=4){let y=.299*data[i]+.587*data[i+1]+.114*data[i+2];if(mode==='gray'){y=Math.min(255,Math.max(0,(y-128)*(1.15+level*.003)+128));out[i]=out[i+1]=out[i+2]=y}else{const threshold=128-(level-50)*.55;const v=y<threshold?0:255;out[i]=out[i+1]=out[i+2]=v}out[i+3]=255}ctx.putImageData(o,0,0);return c}
function openReview(file){pendingScan={file};readImage(file).then(img=>{pendingScan.base=imageToCanvas(img);pendingScan.points=defaultCorners(pendingScan.base);pendingScan.img=img;showReview()}).catch(()=>{$('feedback').textContent='Não foi possível abrir a imagem.'})}
function showReview(){const modal=$('scanReview');modal.showModal();drawReview();$('reviewStatus').textContent='Arraste os quatro cantos para encaixar exatamente na folha.'}
function drawReview(){const c=$('reviewCanvas'),src=pendingScan.base,maxW=Math.min(window.innerWidth-36,900),maxH=Math.min(window.innerHeight-230,650),s=Math.min(maxW/src.width,maxH/src.height);c.width=Math.round(src.width*s);c.height=Math.round(src.height*s);const ctx=c.getContext('2d');ctx.drawImage(src,0,0,c.width,c.height);const pts=pendingScan.points.map(p=>({x:p.x*s,y:p.y*s}));ctx.strokeStyle='#24a7e8';ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();pts.forEach((p,i)=>{ctx.beginPath();ctx.fillStyle='#fff';ctx.strokeStyle='#123047';ctx.lineWidth=3;ctx.arc(p.x,p.y,11,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#123047';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(i+1),p.x,p.y)})}
function reviewPointer(e){if(!pendingScan)return;const c=$('reviewCanvas'),r=c.getBoundingClientRect(),sx=pendingScan.base.width/c.width,sy=pendingScan.base.height/c.height;return{x:(e.clientX-r.left)*sx,y:(e.clientY-r.top)*sy}}
let dragIndex=-1;$('reviewCanvas').addEventListener('pointerdown',e=>{const p=reviewPointer(e);if(!p)return;const sx=$('reviewCanvas').width/pendingScan.base.width;dragIndex=pendingScan.points.findIndex(q=>Math.hypot(q.x*sx-p.x,q.y*sx-p.y)<28);if(dragIndex>=0)$('reviewCanvas').setPointerCapture(e.pointerId)});$('reviewCanvas').addEventListener('pointermove',e=>{if(dragIndex<0)return;const p=reviewPointer(e);pendingScan.points[dragIndex].x=Math.max(0,Math.min(pendingScan.base.width,p.x));pendingScan.points[dragIndex].y=Math.max(0,Math.min(pendingScan.base.height,p.y));drawReview()});$('reviewCanvas').addEventListener('pointerup',()=>dragIndex=-1);$('reviewCanvas').addEventListener('pointercancel',()=>dragIndex=-1);
async function confirmScan(){if(!pendingScan)return false;const mode=document.querySelector('input[name="scanMode"]:checked')?.value||'gray',level=Number($('cleanLevel').value);$('reviewStatus').textContent='Processando documento…';$('confirmScan').disabled=true;await new Promise(r=>setTimeout(r,30));let result=warpPerspectiveJS(pendingScan.base,pendingScan.points);result=processCanvas(result,mode,level);const page={id:newId(),src:canvasData(result,.82),title:'',mode,corrected:true,warning:''};currentDocument.pages.push(page);pendingScan=null;$('scanReview').close();$('confirmScan').disabled=false;renderPages();await saveNow();$('feedback').textContent='Página corrigida e salva neste aparelho.';return true}
async function addFiles(files){const list=[...files].filter(f=>f.type.startsWith('image/'));if(!list.length)return;for(const f of list){openReview(f);await new Promise(resolve=>{const onConfirm=async()=>{cleanup();await confirmScan();resolve()};const onCancel=()=>{cleanup();pendingScan=null;resolve()};const cleanup=()=>{$('confirmScan').removeEventListener('click',onConfirm);$('cancelScan').removeEventListener('click',onCancel);$('closeReview').removeEventListener('click',onCancel)};$('confirmScan').addEventListener('click',onConfirm);$('cancelScan').addEventListener('click',onCancel);$('closeReview').addEventListener('click',onCancel)})}}
function splitText(doc,text,width){return doc.splitTextToSize(text||'—',width)}
function header(doc,page,title,company){doc.setFillColor(18,48,71);doc.rect(0,0,210,22,'F');doc.setTextColor(255);doc.setFontSize(15);doc.setFont(undefined,'bold');doc.text(company||'Blexo-Check',12,14);doc.setFont(undefined,'normal');doc.setFontSize(9);doc.text(`DIGITALIZAÇÃO · ${page}`,198,14,{align:'right'});doc.setTextColor(30,46,56);doc.setFontSize(17);doc.setFont(undefined,'bold');doc.text(title||'Documento',12,35);doc.setFont(undefined,'normal')}
function drawImageA4(doc,src){return new Promise(resolve=>{const img=new Image();img.onload=()=>{const maxW=190,maxH=244,r=Math.min(maxW/img.naturalWidth,maxH/img.naturalHeight),w=img.naturalWidth*r,h=img.naturalHeight*r;doc.addImage(src,'JPEG',(210-w)/2,45+(244-h)/2,w,h,undefined,'FAST');resolve()};img.src=src})}
async function generatePdf(){if(!window.jspdf){$('feedback').textContent='Gerador de PDF indisponível.';return}await saveNow();const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4',compress:true}),title=currentDocument.name||'Documento digitalizado';for(let i=0;i<currentDocument.pages.length;i++){if(i)doc.addPage();header(doc,String(i+1),title,currentDocument.company);if(currentDocument.reference){doc.setFontSize(8.5);doc.setTextColor(100);doc.text(splitText(doc,currentDocument.reference,186),12,40)}await drawImageA4(doc,currentDocument.pages[i].src);if(currentDocument.pages[i].title){doc.setFontSize(8);doc.setTextColor(90);doc.text(currentDocument.pages[i].title,12,292)}}if(currentDocument.notes||currentDocument.responsible){doc.addPage();header(doc,String(currentDocument.pages.length+1),title,currentDocument.company);let y=50;if(currentDocument.responsible){doc.setFontSize(11);doc.setFont(undefined,'bold');doc.text('Responsável',12,y);doc.setFont(undefined,'normal');doc.text(currentDocument.responsible,50,y);y+=12}if(currentDocument.notes){doc.setFont(undefined,'bold');doc.text('Observações finais',12,y);y+=8;doc.setFont(undefined,'normal');doc.setFontSize(9);doc.text(splitText(doc,currentDocument.notes,180),12,y)}}const safe=title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase();doc.save(`blexo-documento-${safe||'digitalizado'}.pdf`);$('feedback').textContent='PDF gerado e download iniciado.'}
['documentName','company','reference','responsible','notes'].forEach(id=>$(id).addEventListener('input',()=>{syncFields();scheduleSave()}));$('cameraInput').addEventListener('change',e=>{addFiles(e.target.files);e.target.value=''});$('galleryInput').addEventListener('change',e=>{addFiles(e.target.files);e.target.value=''});$('generateButton').onclick=generatePdf;$('cleanLevel').addEventListener('input',()=>{updateCleanLabel();syncFields();scheduleSave()});document.querySelectorAll('input[name="scanMode"]').forEach(r=>r.addEventListener('change',()=>{syncFields();scheduleSave('Modo de tratamento alterado.')}));$('cancelScan').onclick=()=>{$('scanReview').close();pendingScan=null};$('closeReview').onclick=()=>{$('scanReview').close();pendingScan=null};window.addEventListener('resize',()=>{if($('scanReview').open&&pendingScan)drawReview()});window.addEventListener('online',setOnlineStatus);window.addEventListener('offline',setOnlineStatus);function setOnlineStatus(){const on=navigator.onLine;$('offlineStatus').textContent=on?'● Online':'● Offline';$('offlineStatus').classList.toggle('offline',!on)}
(async()=>{try{const docs=await getDocuments();if(docs.length)currentDocument=docs.sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt))[0];render();setOnlineStatus()}catch{render();setOnlineStatus()}})();
