const BLEXO_GOOGLE_SCOPE='https://www.googleapis.com/auth/drive.file';let blexoGoogleToken='';
function blexoGoogleConfig(){return typeof blexoConfig==='function'?blexoConfig():{}}
function blexoLoadGoogle(){return new Promise((ok,no)=>{if(window.google?.accounts?.oauth2)return ok();let s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=ok;s.onerror=()=>no(new Error('Não foi possível carregar o Google'));document.head.appendChild(s)})}
async function blexoConnectGoogle(){let c=blexoGoogleConfig();if(!c.googleClientId)throw new Error('Informe o Client ID do Google nas Configurações.');await blexoLoadGoogle();return new Promise((ok,no)=>{let tc=google.accounts.oauth2.initTokenClient({client_id:c.googleClientId,scope:BLEXO_GOOGLE_SCOPE,callback:r=>{if(r.error)no(new Error(r.error));else{blexoGoogleToken=r.access_token;localStorage.setItem('blexo-google-status','Conectado ao Google');ok(r)}}});tc.requestAccessToken({prompt:''})})}
async function df(url,o={}){if(!blexoGoogleToken)await blexoConnectGoogle();o.headers={...(o.headers||{}),Authorization:'Bearer '+blexoGoogleToken};let r=await fetch(url,o);if(!r.ok)throw new Error('Google Drive: '+r.status);return r}
async function folder(name,parent){let q=encodeURIComponent(`name='${name}' and mimeType='application/vnd.google-apps.folder' and trashed=false${parent?` and '${parent}' in parents`:''}`),j=await(await df('https://www.googleapis.com/drive/v3/files?q='+q+'&fields=files(id)')).json();if(j.files?.[0])return j.files[0].id;let meta={name,mimeType:'application/vnd.google-apps.folder'};if(parent)meta.parents=[parent];let fd=new FormData();fd.append('metadata',new Blob([JSON.stringify(meta)],{type:'application/json'}));fd.append('file',new Blob(['']));return(await(await df('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',{method:'POST',body:fd})).json()).id}
async function blexoDrivePath(module){let root=await folder(blexoGoogleConfig().googleDriveFolder||'Blexo Suite');return folder(module,root)}
async function blexoUploadJson(module,name,data){let parent=await blexoDrivePath(module),fn=name+'.json',q=encodeURIComponent(`name='${fn}' and '${parent}' in parents and trashed=false`),j=await(await df('https://www.googleapis.com/drive/v3/files?q='+q+'&fields=files(id)')).json(),meta={name:fn,mimeType:'application/json',parents:[parent]},fd=new FormData();fd.append('metadata',new Blob([JSON.stringify(meta)],{type:'application/json'}));fd.append('file',new Blob([JSON.stringify(data)],{type:'application/json'}));let base='https://www.googleapis.com/upload/drive/v3/files',url=j.files?.[0]?base+'/'+j.files[0].id+'?uploadType=multipart':base+'?uploadType=multipart';await df(url,{method:j.files?.[0]?'PATCH':'POST',body:fd})}
async function blexoSyncModule(module,getAll,put){let local=await getAll();for(let x of local)await blexoUploadJson(module,x.id||x.number||crypto.randomUUID(),x);return{uploaded:local.length}}
