const $=id=>document.getElementById(id);let ronda=null,selectedPoint=null;const KEY='blexo-ronda-current-v1';
function cfg(){return typeof blexoConfig==='function'?blexoConfig():{blockCount:26,rondaAreas:[]}}
function fmt(d){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(d))}
function makePoints(){const c=cfg(), blocks=Array.from({length:Number(c.blockCount)||26},(_,i)=>({name:`Bloco ${String(i+1).padStart(2,'0')}`,photo:null,at:null}));return [...blocks,...(c.rondaAreas||[]).map(name=>({name,photo:null,at:null}))]}
function newRonda(){ronda={id:Date.now(),startedAt:new Date().toISOString(),vigilante:'',notes:'',points:makePoints()};save();render()}
function save(){if(ronda)localStorage.setItem(KEY,JSON.stringify(ronda))}
function load(){try{ronda=JSON.parse(localStorage.getItem(KEY)||'null')}catch{} if(!ronda)newRonda()}
function render(){if(!ronda)return;$('vigilante').value=ronda.vigilante||'';$('notes').value=ronda.notes||'';$('startedAt').textContent=fmt(ronda.startedAt);const done=ronda.points.filter(p=>p.photo).length;$('progress').textContent=`${done}/${ronda.points.length} pontos`;$('pdfButton').disabled=done===0;const box=$('points');box.innerHTML='';ronda.points.forEach((p,i)=>{const row=document.createElement('div');row.className='point '+(p.photo?'done':'');row.innerHTML=`<span class="point-index">${i+1}</span><div><div class="point-name">${p.name}</div><div class="point-status">${p.photo?'✓ Fotografado em '+fmt(p.at):'Pendente'}</div></div><button type="button">${p.photo?'Refazer foto':'📷 Fotografar'}</button>${p.photo?`<img src="${p.photo}" alt="${p.name}">`:''}`;row.querySelector('button').onclick=()=>{selectedPoint=i;$('cameraInput').click()};box.appendChild(row)})}
$('cameraInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f||selectedPoint===null)return;const reader=new FileReader();reader.onload=()=>{ronda.points[selectedPoint].photo=reader.result;ronda.points[selectedPoint].at=new Date().toISOString();save();render();selectedPoint=null};reader.readAsDataURL(f);e.target.value=''})
$('vigilante').addEventListener('input',e=>{ronda.vigilante=e.target.value;save()});$('notes').addEventListener('input',e=>{ronda.notes=e.target.value;save()});$('startButton').onclick=()=>{if(confirm('Iniciar uma nova ronda? A ronda atual continuará salva apenas se você cancelar.'))newRonda()};
$('pdfButton').onclick=()=>generatePdf();
function addHeader(doc,page){const c=cfg(), color=(c.rondaHeaderColor||'#123047').replace('#','');const r=parseInt(color.slice(0,2),16),g=parseInt(color.slice(2,4),16),b=parseInt(color.slice(4,6),16);doc.setFillColor(r,g,b);doc.rect(0,0,210,20,'F');doc.setTextColor(255);doc.setFontSize(15);doc.text(c.rondaHeaderName||'Blexo-Ronda',12,13);doc.setFontSize(9);doc.text(`RONDA · ${page}`,198,13,{align:'right'});doc.setTextColor(35,45,55)}
function generatePdf(){if(!ronda.points.some(p=>p.photo))return;const {jsPDF}=window.jspdf,doc=new jsPDF('p','mm','a4');const points=ronda.points.filter(p=>p.photo);let page=1,idx=0;while(idx<points.length){if(idx>0){doc.addPage();page++}addHeader(doc,page);doc.setFontSize(15);doc.text('Registro de Ronda',12,31);doc.setFontSize(10);doc.text(`Vigilante: ${ronda.vigilante||'Não informado'}`,12,39);doc.text(`Início: ${fmt(ronda.startedAt)}`,12,45);for(let slot=0;slot<6&&idx<points.length;slot++,idx++){const p=points[idx],col=slot%2,row=Math.floor(slot/2),x=12+col*94,y=51+row*78;doc.addImage(p.photo,'JPEG',x,y,88,59,undefined,'FAST');doc.setFontSize(10);doc.text(p.name,x,y+64);doc.setFontSize(8);doc.text(fmt(p.at),x,y+69)}if(idx>=points.length&&ronda.notes.trim()){const y=285;doc.setFontSize(9);doc.text('Observações gerais:',12,y);doc.setFontSize(8);doc.text(doc.splitTextToSize(ronda.notes,185),12,y+5)} }doc.save(`Ronda-${new Date(ronda.startedAt).toLocaleDateString('pt-BR').replaceAll('/','-')}.pdf`);$('feedback').textContent='PDF gerado. O arquivo foi enviado para download e pode ser salvo no aparelho.'}
function online(){const on=navigator.onLine;$('offlineStatus').textContent=on?'● Online':'● Offline';$('offlineStatus').classList.toggle('offline',!on)}window.addEventListener('online',online);window.addEventListener('offline',online);online();load();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
